In [30]:
import pandas as pd
import numpy as np

In [31]:
df=pd.read_csv(r"C:\Users\gourav verma\OneDrive\Desktop\python for ML\crime(1).csv")

In [32]:
df

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,DISTRICT,REPORTING_AREA,OCCURRED_ON_DATE,STREET,Lat,Long,NAME
0,I182070945,619,Larceny,D14,808,02-09-2018 13:00,LINCOLN ST,42.357791,-71.139371,LARCENY OTHER $200 & OVER
1,I182070885,619,Larceny,B3,456,03-09-2018 17:17,ELLINGTON ST,42.301546,-71.081182,LARCENY OTHER $200 & OVER
2,I182070816,619,Larceny,C6,185,03-09-2018 12:45,MASSACHUSETTS AVE,42.321987,-71.062807,LARCENY OTHER $200 & OVER
3,I182070777,619,Larceny,C11,388,23-08-2018 13:34,ADAMS ST,42.272306,-71.067214,LARCENY OTHER $200 & OVER
4,I182070707,619,Larceny,D14,782,02-09-2018 23:12,GORDON ST,42.352935,-71.140501,LARCENY OTHER $200 & OVER
...,...,...,...,...,...,...,...,...,...,...
313632,I130126035-00,338,Robbery,C11,252,09-02-2016 13:55,SAVIN HILL AV,NaN,NaN,ROBBERY - UNARMED - RESIDENCE
313633,I130041200-00,547,Burglary - No Property Taken,B3,428,07-12-2015 11:38,DIXWELL ST,42.314334,-71.097914,B&E NON-RESIDENCE DAY - NO PROP TAKEN
313634,I120720047-00,334,Robbery,E13,565,17-07-2015 09:23,NaN,NaN,NaN,ROBBERY - UNARMED - BUSINESS
313635,I120719309-00,530,Commercial Burglary,A1,119,27-07-2015 12:00,BOYLSTON ST,42.352418,-71.065255,B&E NON-RESIDENCE NIGHT - FORCE
313636,I060168073-00,1864,Drug Violation,E13,912,27-01-2018 14:01,CENTRE ST,42.322838,-71.100967,DRUGS - POSS CLASS D - INTENT MFR DIST DISP

In [33]:
df.isna().sum()

INCIDENT_NUMBER           0
OFFENSE_CODE              0
OFFENSE_CODE_GROUP        0
DISTRICT               1708
REPORTING_AREA            0
OCCURRED_ON_DATE          0
STREET                10505
Lat                   19360
Long                  19360
NAME                      0
dtype: int64

In [34]:
df[df.duplicated()]

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,DISTRICT,REPORTING_AREA,OCCURRED_ON_DATE,STREET,Lat,Long,NAME
21123,I142049917-00,1402,Vandalism,C11,395,03-09-2015 13:00,DORCHESTER AVE,42.285260,-71.064441,VANDALISM
48820,I120470733-00,724,Auto Theft,C6,205,23-09-2016 19:15,A ST,42.346953,-71.051127,AUTO THEFT
122550,I130041200-00,522,Residential Burglary,B3,428,07-12-2015 11:38,DIXWELL ST,42.314334,-71.097914,B&E RESIDENCE DAY - NO FORCE
153665,I142020701-00,802,Simple Assault,C11,337,14-10-2015 01:00,COLUMBIA RD,42.306451,-71.077304,ASSAULT & BATTERY
153671,I120189428-00,802,Simple Assault,E13,303,09-12-2015 18:35,AMORY ST,42.318245,-71.101268,ASSAULT & BATTERY
174541,I142016089-00,613,Larceny,C11,388,10-10-2015 09:30,DORCHESTER AVE,42.278399,-71.066363,LARCENY SHOPLIFTING $200 & OVER
187622,I152030570-00,3125,Warrant Arrests,E13,303,29-10-2016 08:25,W WALNUT PARK,42.317207,-71.098799,WARRANT ARREST
187626,I152026488-00,3125,Warrant Arrests,A1,105,31-01-2017 10:00,FRUIT ST,42.362403,-71.069547,WARRANT ARREST
187637,I152004688-00,3125,Warrant Arrests,A1,120,19-07-2016 12:50,BOYLSTON ST,42.352418,-71.065255,WARRANT ARREST
187645,I142060752-00,3125,Warrant Arrests,B2,280,11-12-2015 12:50,DUDLEY ST,42.328726,-71.083822,WARRANT ARREST
187666,I142025900-00,3125,Warrant Arrests,E13,577,01-12-2015 18:00,AMORY ST,42.317713,-71.101805,WARRANT ARREST
187674,I142017108-00,3125,Warrant Arrests,A1,64,16-06-2015 15:55,FRUIT ST,42.362403,-71.069547,WARRANT ARREST
187677,I142014620-00,3125,Warrant Arrests,A1,112,18-08-2015 01:10,WASHINGTON ST,42.354564,-71.061474,WARRANT ARREST
187692,I140056633-00,3125,Warrant Arrests,A1,64,16-06-2015 15:55,FRUIT ST,42.362403,-71.069547,WARRANT ARREST
187696,I140039570-00,3125,Warrant Arrests,A1,103,28-09-2015 11:15,WASHINGTON ST,42.356486,-71.059281,WARRANT ARREST
187698,I140036361-00,3125,Warrant Arrests,E5,680,10-07-2015 10:15,CORINTH ST,42.286369,-71.130055,WARRANT ARREST
187708,I130371627-00,3125,Warrant Arrests,B2,318,02-10-2015 21:00,HOMESTEAD ST,42.311277,-71.089093,WARRANT ARREST
187713,I130202615-00,3125,Warrant Arrests,B2,587,03-08-2015 17:23,BURNEY ST,42.331496,-71.099791,WARRANT ARREST
187716,I130041200-00,3125,Warrant Arrests,B3,428,07-12-2015 11:38,DIXWELL ST,42.314334,-71.097914,WARRANT ARREST
187732,I110177502-00,3125,Warrant Arrests,B2,318,02-10-2015 21:00,HOMESTEAD ST,42.311277,-71.089093,WARRANT ARREST
187737,I090321958-00,3125,Warrant Arrests,C11,355,01-02-2016 01:43,GENEVA AVE,NaN,NaN,WARRANT ARREST
189070,I142017108-00,1841,Drug Violation,A1,64,16-06-2015 15:55,FRUIT ST,42.362403,-71.069547,DRUGS - POSS CLASS A - INTENT TO MFR DIST DISP
198432,I130731947-00,2405,Disorderly Conduct,D4,172,22-07-2015 22:00,MASSACHUSETTS AVE,42.333391,-71.073120,DISORDERLY PERSON
207504,I130194606-00,617,Larceny,D4,136,02-02-2016 19:30,COMMONWEALTH AVE,42.351153,-71.081614,LARCENY IN A BUILDING $200 & OVER
231238,I152026775-00,3115,Investigate Person,C6,936,19-10-2015 16:04,ORTON-MAROTTA WAY,42.338573,-71.055755,INVESTIGATE PERSON
241241,I152006153-00,1849,Drug Violation,C6,179,16-09-2015 11:30,MASSACHUSETTS AVE,42.332531,-71.072130,"DRUGS - POSS CLASS B - COCAINE, ETC."
241248,I140346143-00,1849,Drug Violation,E18,490,07-01-2017 20:00,AMERICAN LEGION HWY,42.275313,-71.115878,"DRUGS - POSS CLASS B - COCAINE, ETC."
246721,I142033219-00,1842,Drug Violation,D4,171,04-01-2016 17:20,HARRISON AVE,42.335119,-71.074917,"DRUGS - POSS CLASS A - HEROIN, ETC."
262473,I142060752-00,2610,Other,B2,280,11-12-2015 12:50,DUDLEY ST,42.328726,-71.083822,TRESPASSING
262479,I130731947-00,2610,Other,D4,172,22-07-2015 22:00,MASSACHUSETTS AVE,42.333391,-71.073120,TRESPASSING
294669,I152000618-00,1503,Firearm Violations,B2,308,20-07-2015 18:48,BOWER ST,42.319968,-71.087150,FIREARM/WEAPON - POSSESSION OF DANGEROUS
297483,I152041086-00,2407,Disorderly Conduct,A1,111,17-08-2015 13:00,BOYLSTON ST,42.352368,-71.064543,ANNOYING AND ACCOSTIN

In [35]:
df[df.duplicated()].shape

(32, 10)

In [36]:
dup=df[df.duplicated()].shape

In [37]:
dup=df[df.duplicated()]
dup.to_csv("duplicatescrime.csv",index=False)
df.drop_duplicates(inplace=True)

In [38]:
df.isna().sum()

INCIDENT_NUMBER           0
OFFENSE_CODE              0
OFFENSE_CODE_GROUP        0
DISTRICT               1708
REPORTING_AREA            0
OCCURRED_ON_DATE          0
STREET                10505
Lat                   19359
Long                  19359
NAME                      0
dtype: int64

In [39]:
df["DISTRICT"].unique().tolist()

['D14',
 'B3',
 'C6',
 'C11',
 'D4',
 'E18',
 'B2',
 'A1',
 'E5',
 'A15',
 'E13',
 'A7',
 nan]

In [40]:
df["STREET"].unique().tolist()

['LINCOLN ST',
 'ELLINGTON ST',
 'MASSACHUSETTS AVE',
 'ADAMS ST',
 'GORDON ST',
 'COMMONWEALTH AVE',
 'WALTER ST',
 'F ST',
 'TALBOT AVE',
 'ALLSTATE RD',
 'SEAVER ST',
 'CAMBRIDGE ST',
 'WASHINGTON ST',
 'BURNEY ST',
 'FAIRMOUNT ST',
 'MONTCALM AVE',
 'BOYLSTON ST',
 'BRIGHTON AVE',
 'SCHOOL ST',
 'FANEUIL HALL MARKETPLACE',
 'BEACON ST',
 'DALE ST',
 'RIDGEWOOD ST',
 'CHESTER ST',
 'CITY HALL PLZ',
 'BAKERSFIELD ST',
 'SOUTH ST',
 'WILLERS ST',
 'CHARLES ST',
 'MATTAPAN ST',
 'TREMONT ST',
 'CONCORD SQ',
 'RIVERVIEW RD',
 'E CANTON ST',
 'SUMMER ST',
 'BLUE HILL AVE',
 'WOODROW AVE',
 'E BROADWAY',
 'PEARL ST',
 'WILLIAM T MORRISSEY BLVD',
 'WALFORD WAY',
 'PIER 4',
 'JULIAN ST',
 'GREENHEYS ST',
 'LONGWOOD AVE',
 nan,
 'COOPER ST',
 'CENTRE ST',
 'BRECK AVE',
 'CORNELL ST',
 'BLACKSTONE ST',
 'AMERICAN LEGION HWY',
 'MCGREEVEY WAY',
 'CEDAR ST',
 'EDWIN ST',
 'PASADENA RD',
 'PARK DR',
 'BINNEY ST',
 'COLBORNE RD',
 'FESSENDEN ST',
 'GLEN RD',
 'DARTMOUTH ST',
 'HYDE PARK AVE',
 'FENWAY',
 'NEWBURY ST',
 'L ST',
 'PUBLIC ALLEY NO 543',
 'COTTAGE ST',
 'CEYLON ST',
 'RIVER ST',
 'QUEENSBERRY ST',
 'FRENCH TER',
 'KENILWORTH ST',
 'READING ST',
 'DENNISON ST',
 'LANSDOWNE ST',
 'HARRISON AVE',
 'BAKER ST',
 'E INDIA ROW',
 'FOTTLER RD',
 'MEREDITH ST',
 'KINGSTON ST',
 'OXFORD PL',
 'ROXBURY ST',
 'KNEELAND ST',
 'MICHIGAN AVE',
 'D ST',
 'SHEPTON ST',
 'PIERCE ST',
 'FARADAY ST',
 'ALBANY ST',
 'FORT AVE',
 'MARION',
 'ATLANTIC AVE',
 'HALL ST',
 'G ST',
 'CENTRAL AVE',
 'HENRY STERLING SQ',
 'GARFIELD AVE',
 'BRUNSWICK ST',
 'MANSUR ST',
 'GARRISON ST',
 'AUSTIN ST',
 'GENERAL LAWRENCE J LOGAN ',
 'STATE ST',
 'TRENTON ST',
 'LEXINGTON ST',
 'WHITMAN ST',
 'ROSECLAIR ST',
 'ASHMONT ST',
 'KILMARNOCK ST',
 'HANSBOROUGH ST',
 'MARGO RD',
 'FANEUIL HALL SQ',
 'BROOKLINE AVE',
 'GRANFIELD AVE',
 'ROBINWOOD AVE',
 'E EIGHTH ST',
 'HOLBORN ST',
 'ISLAND VIEW PL',
 'DUDLEY ST',
 'HOMESTEAD ST',
 'APPLETON ST',
 'WESTINGHOUSE PLZ',
 'OLD COLONY AVE',
 'BELVIDERE ST',
 'MORTON ST',
 'MURDOCK TER',
 'LEDGEMERE RD',
 'ESSEX ST',
 'SENATOR BOLLING CIR',
 'CHAUNCY ST',
 'DEVON ST',
 'ALGONQUIN ST',
 'W NINTH ST',
 'LANARK RD',
 'OLD MORTON ST',
 'RIVERWAY',
 'HEMENWAY ST',
 'BOSTON ST',
 'K ST',
 'LEWIS ST',
 'FAIRMOUNT AVE',
 'WAYLAND ST',
 'FULTON ST',
 'WINTER ST',
 'ORIENT AVE',
 'CANAL ST',
 'W THIRD ST',
 'FATHER FRANCIS J GILDAY S',
 'DIX ST',
 'WHEATLAND',
 'TOPLIFF ST',
 'BROADWAY',
 'GLOUCESTER ST',
 'E ST',
 'BARROWS',
 'WYMAN ST',
 'DORCHESTER ST',
 'CHESTNUT AVE',
 'WILLIAM F MCCLELLAN HWY',
 'GENEVA AVE',
 'N HARVARD ST',
 'PAUL PL',
 'EAST ST',
 'SAXTON ST',
 'PARKER ST',
 'WALDECK ST',
 'BRAYTON RD',
 'HUNTINGTON AVE',
 'BEACH ST',
 'WELLSMERE RD',
 'ARMSTRONG ST',
 'MANOR ST',
 'GLADSTONE ST',
 'DORCHESTER AVE',
 'CENTRE',
 'PARK ST',
 'E SECOND ST',
 'GIBSON ST',
 'E FIFTH ST',
 'LEXINGTON',
 'SCHUYLER ST',
 'GORDON AVE',
 'WARREN ST',
 'OAKVIEW TER',
 'CHESTNUT ST',
 'GOVE ST',
 'PARTRIDGE ST',
 'CUNARD WAY',
 'ROCKLEDGE ST',
 'SOUTHAMPTON ST',
 'E FIRST ST',
 'CHARLOTTE ST',
 'W BELLFLOWER ST',
 'N MARGIN ST',
 'LAMARTINE ST',
 'WORTHINGTON ST',
 'MONADNOCK ST',
 'WORCESTER SQ',
 'WEST ST',
 'DAY ST',
 'FARNHAM ST',
 'HOMES AVE',
 'WILLIAMS AVE',
 'CHELSEA ST',
 'W CANTON ST',
 'HANOVER ST',
 'CHESTNUT HILL AVE',
 'COLUMBUS AVE',
 'S MUNROE TER',
 'SAVIN HILL AVE',
 'CONGRESS ST',
 'ALLEGHANY ST',
 'WINSTON RD',
 'DEERING RD',
 'MESSINGER ST',
 'MORTON',
 'NORTON ST',
 'VOGEL ST',
 'BROAD ST',
 'WESTMOOR RD',
 'JERSEY ST',
 'ALLSTON ST',
 'MONSIGNOR ALBERT A. JACOB',
 'MILK ST',
 'HAVILAND ST',
 'E CONCORD ST',
 'COREY RD',
 'GOLD ST',
 'GRASSMERE RD',
 'DRAPER ST',
 'MARDEN AVE',
 'OLDFIELDS RD',
 'TEMPLE PL',
 'CLINTON ST',
 'CLARKSON ST',
 'HANCOCK ST',
 'NEW SUDBURY ST',
 'WESTLAND AVE',
 'REGIS RD',
 'HANSFORD ST',
 'EUTAW ST',
 'CAPEN PL',
 'IRVING ST',
 'CATBIRD CT',
 'JAN KARSKI WAY',
 'OSPREY WAY',
 'MILLET ST',
 'THORNTON ST',
 'REV RICHARD A BURKE ST',
 'CHILD ST',
 'DUNCAN ST',
 'LAMBERT AVE',
 'AVENUE DE LAFAYETTE',
 'BOSTON WHARF RD',
 'SUMNER ST',
 'SAINT JAMES ST',
 'MAVERICK SQ',
 'FIRST AVE',
 'QUINT AVE',
 'ARROW ST',
 'WHEATLEY WAY',
 'FARRAGUT RD',
 'CHATHAM ST',
 'PERHAM ST',
 'SUSANNA CT',
 'JOHN ELIOT SQ',
 'WALK HILL ST',
 'HAMILTON ST',
 'EVANS ST',
 'NORFOLK AVE',
 'LANGLEY RD',
 'LEGENDS WAY',
 'WYOMING ST',
 'SHAWMUT AVE',
 'VILLAGE CT',
 'CLARENDON ST',
 'ALABAMA ST',
 'RUGGLES ST',
 'JOHNSTON RD',
 'MINDEN ST',
 'BURBANK ST',
 'PIERPONT RD',
 'MEYER ST',
 'FAYWOOD AVE',
 'MOUNT EVERETT ST',
 'RECTOR RD',
 'GLENVILLE AVE',
 'LYNDHURST ST',
 'GALLIVAN BLVD',
 'FANEUIL ST',
 'GREEN ST',
 'MARTIN LUTHER KING JR BLV',
 'MAGAZINE ST',
 'HALLAM ST',
 'SARGENT ST',
 'WESTMINSTER ST',
 'MONUMENT SQ',
 'WALNUT AVE',
 'MYRTLE ST',
 'HALLIDAY ST',
 'AURIGA ST',
 'STUART ST',
 'VOSE AVE',
 'W SPRINGFIELD ST',
 'POPLAR ST',
 'LYON ST',
 'MAYNARD ST',
 'AUBURN ST',
 'CROWN POINT DR',
 'SHERIDAN ST',
 'STRATHMORE RD',
 'E SPRINGFIELD ST',
 'MCBRIDE ST',
 'W ROXBURY PKWY',
 'FOREST ST',
 'CONCORD AVE',
 'WINTER PL',
 'HOWARD AVE',
 'GLADE AVE',
 'TOWNSEND ST',
 'E NEWTON ST',
 'OXFORD ST',
 'EVERETT AVE',
 'ADELAIDE ST',
 'LAGRANGE ST',
 'COLUMBIA RD',
 'WILDWOOD ST',
 'EDEN ST',
 'HEATH ST',
 'CORDIS ST',
 'DRESSER ST',
 'CONCORD ST',
 'DICKENS ST',
 'FAULKNER ST',
 'PARKMAN ST',
 'FOREST HILLS ST',
 'WAUMBECK ST',
 'HERALD ST',
 'ROWENA ST',
 'BURT ST',
 'TAFT ST',
 'FRAWLEY ST',
 'ASHTON ST',
 'HARVARD AVE',
 'MILTON TER',
 'BERKELEY ST',
 'ROWES WHRF',
 'BOWDOIN ST',
 'HIGH ST',
 'POND ST',
 'CUSTER ST',
 'SURREY ST',
 'BURRELL ST',
 'CRESTWOOD PARK',
 'MONTGOMERY ST',
 'FORSYTH ST',
 'WOODHAVEN ST',
 'BLUE LEDGE DR',
 'MALDEN ST',
 'MORA ST',
 'E FOURTH ST',
 'CEDRUS AVE',
 'STRATTON ST',
 'BIGELOW ST',
 'MORELAND ST',
 'W SEVENTH ST',
 'ELLIS ST',
 'GREENWOOD AVE',
 'SAINT STEPHEN ST',
 'MCKINLEY SQ',
 'WALES ST',
 'H ST',
 'GEORGETOWNE PL',
 'SARATOGA ST',
 'BLAKE ST',
 'BROWN TER',
 'SALEM ST',
 'SOUTHBOURNE RD',
 'CONDOR ST',
 'HARVARD ST',
 'LEVERETT AVE',
 'STEDMAN ST',
 'STANIFORD ST',
 'WESTVILLE ST',
 'SUNSET ST',
 'FREEPORT ST',
 'GOODALE RD',
 'TELEGRAPH ST',
 'PEMBERTON SQ',
 'CUMMINS HWY',
 'HOWLAND ST',
 'FREEPORT WAY',
 'ROCKLAND ST',
 'SOLDIERS FIELD RD',
 'WHITFIELD ST',
 'OLD RD',
 'LONGFELLOW ST',
 'WESTGATE RD',
 'CAUSEWAY ST',
 'HALLET ST',
 'SHIRLEY ST',
 'BAY STATE RD',
 'MERIDIAN ST',
 'EVERETT ST',
 'TYLER ST',
 'STANDARD ST',
 'W MILTON ST',
 'MAYHEW ST',
 'FRANKLIN ST',
 'DANFORTH ST',
 'HARVEST ST',
 'N ST',
 'PEMBROKE ST',
 'WELLINGTON HILL ST',
 'SAINT JAMES AVE',
 'CASTLEGATE RD',
 'ARCOLA ST',
 'BUSINESS ST',
 'VALLAR RD',
 'W NEWTON ST',
 'DAKOTA ST',
 'UNION PARK ST',
 'BEECHER ST',
 'EDGEMERE RD',
 'LEYLAND ST',
 'SOMERSET ST',
 'PARKER HILL AVE',
 'MARKET ST',
 'BOWKER ST',
 'NEW WHITNEY ST',
 'SEAPORT BLVD',
 'NORWELL ST',
 'CHANDLER ST',
 'DANA AVE',
 'ORKNEY RD',
 'I ST',
 'GREENVILLE ST',
 'BRACKETT ST',
 'GLENWOOD AVE',
 'EDISON GRN',
 'MOUNT CUSHING TER',
 'WESTCOTT ST',
 'PRINCETON ST',
 'CLIFFMONT ST',
 'GATES ST',
 'ROSEDALE ST',
 'LIME ST',
 'BUNKER HILL',
 'OLIVER ST',
 'WARD ST',
 'BENNETT ST',
 'EASTON AVE',
 'PURITAN AVE',
 'DUNSTABLE ST',
 'HAVRE ST',
 'ARBORWAY',
 'REDLANDS RD',
 'MASCOT ST',
 'ROWE ST',
 'PLEASANT ST',
 'PORTER ST',
 'BELGRADE AVE',
 'COLEUS PARK',
 'DEFOREST ST',
 'TRUMAN PKWY',
 'SALCOMBE ST',
 'SAINT MARGARET ST',
 'HARTWELL ST',
 'BAKER CT',
 'EGLESTON ST',
 'CAMDEN ST',
 'NORTHAMPTON ST',
 'MARLBOROUGH ST',
 'DWIGHT ST',
 'ALBEMARLE ST',
 'AMORY AVE',
 'MELVIN AVE',
 'NOTTINGHILL RD',
 'PERTHSHIRE RD',
 'JEROME ST',
 'RAWSON ST',
 'CANTERBURY ST',
 'OAKWOOD ST',
 'BENNINGTON ST',
 'PETERBOROUGH ST',
 'NORTHERN AVE',
 'HOOPER ST',
 'ERIE ST',
 'DITSON ST',
 'HOUGHTON ST',
 'MCLELLAN ST',
 'MALLARD AVE',
 'ORCHARDFIELD ST',
 'BISHOP ST',
 'MORSE ST',
 'MELVILLE AVE',
 'POMPEII ST',
 'BROOKS ST',
 'LINDSEY ST',
 'S HUNTINGTON AVE',
 'MELNEA CASS BLVD',
 'GAYLORD ST',
 'SPRAGUE ST',
 'ESTRELLA ST',
 'NORTH ST',
 'PILGRIM RD',
 'TURTLE POND PKWY',
 'ELMHURST ST',
 'CHAMBLET ST',
 'SYMPHONY RD',
 'HARRISON ARCHWAYS',
 'BERNARD ST',
 'E BERKELEY ST',
 'MADISON ST',
 'ASHBURTON PL',
 'GREENWICH PARK',
 'ERNST ST',
 'FORBES ST',
 'MONUMENT ST',
 'WINDERMERE RD',
 'BAYSWATER ST',
 'BASILE ST',
 'BATTERY WHRF',
 'W MAIN ST',
 'LUCERNE ST',
 'HOWES ST',
 'JOY ST',
 'PENINSULA PL',
 'WOODVILLE PARK',
 'DELLE AVE',
 'PARK PLZ',
 'EDWARDSON ST',
 'COURTLAND RD',
 'CALUMET ST',
 'PROSPECT CIR',
 'GLENHAVEN RD',
 'N BEACON ST',
 'ROCKVALE CIR',
 'DUSTIN ST',
 'PALMER ST',
 'MONMOUTH ST',
 'FAIRLAWN AVE',
 'LONG AVE',
 'PROVIDENCE ST',
 'TEMPLE ST',
 'BEECH GLEN ST',
 'ALWIN ST',
 'W CONCORD ST',
 'SAGAMORE ST',
 'WOODBINE ST',
 'E EAGLE ST',
 'MAVERICK ST',
 'ALPINE ST',
 'ROSELAND ST',
 'W BROADWAY',
 'KELTON ST',
 'DALTON ST',
 'AUCKLAND ST',
 'BEALE ST',
 'CRAWFORD ST',
 'COBDEN ST',
 'HARRISHOF ST',
 'JOSEPHINE ST',
 'TOWER ST',
 'BROOKVALE ST',
 'IROQUOIS ST',
 'E THIRD ST',
 'PHILBRICK ST',
 'BOSTONIA AVE',
 'FIDELIS WAY',
 'CEDRIC ST',
 'MORAINE ST',
 'GRAYFIELD AVE',
 'FANEUIL',
 'HOOKER ST',
 'BICKFORD ST',
 'READVILLE ST',
 'COMMERCIAL ST',
 'THACHER ST',
 'MILL ST',
 'VINTON ST',
 'ORLANDO ST',
 'HILLSIDE ST',
 'DALESSIO CT',
 'STILLMAN ST',
 'LOCHSTEAD AVE',
 'FENWOOD RD',
 'BROOK FARM RD',
 'ZEIGLER ST',
 'QUINCY ST',
 'VASSAR ST',
 'WARREN PARK',
 'MAGNOLIA SQ',
 'BREWER ST',
 'BRADSHAW ST',
 'ARION ST',
 'DALRYMPLE ST',
 'FALCON ST',
 'OAKRIDGE ST',
 'ELIOT ST',
 'GRAMPIAN WAY',
 'BUNKER HILL ST',
 'DURHAM ST',
 'OLNEY ST',
 'KITTREDGE ST',
 'GLENWAY ST',
 'JULIETTE ST',
 'GROVE ST',
 'ALVESTON TER',
 'HARTFORD ST',
 'CLERMONT ST',
 'O ST',
 'COLONIAL AVE',
 'HAMMOND ST',
 'WORCESTER ST',
 'SAINT WILLIAM ST',
 'ATHERTON ST',
 'MONUMENT AVE',
 'SAINT GERMAIN ST',
 'CHARLESGATE W',
 'MURDOCK ST',
 'RICHFIELD ST',
 'BORDER ST',
 "MONSIGNOR DENNIS F O'CALL",
 'ARCH ST',
 'HOLDEN ST',
 'ISLAND ST',
 'HILL TOP ST',
 'ARCADIA ST',
 'MAYFIELD ST',
 'SIXTEENTH ST',
 'GREENWICH ST',
 'BOYNTON ST',
 'FOSTER ST',
 'ROSSETER ST',
 'FRANCIS ST',
 'RICH ST',
 'BARDWELL ST',
 'MOULTRIE ST',
 'ORLEANS ST',
 'MEDFORD ST',
 'MONTEBELLO RD',
 'W HOWELL ST',
 'THORNLEY ST',
 'KENDALL ST',
 'WRENTHAM ST',
 'WOODCLIFF ST',
 'WARREN AVE',
 'GAY HEAD ST',
 'BRAGDON ST',
 'HIGHLAND ST',
 'NEW CHARDON ST',
 'CENTER PLZ',
 'HUMBOLDT AVE',
 'TRENT ST',
 'GERALD RD',
 'CHILCOTT PL',
 'VFW PKWY',
 'BABSON ST',
 'LITHGOW ST',
 'MAPLE ST',
 'BEVERLY ST',
 'ASHFORD ST',
 'EIGHTH ST',
 'PRATT ST',
 'PEACEVALE RD',
 'NORFOLK ST',
 "O'BRIEN CT",
 'SYCAMORE ST',
 'WOODSTOCK AVE',
 'RUTLAND',
 'W FIFTH ST',
 'PONTIAC ST',
 'TRULL ST',
 'FULLER ST',
 'RUSKINDALE RD',
 'BEETHOVEN ST',
 'MAPLEWOOD ST',
 'BOYLSTON',
 'PAGE ST',
 'FLORIDA ST',
 'CAMELOT CT',
 'VICKSBURG ST',
 'NEWCOMB ST',
 'AVERY ST',
 'STORY ST',
 'FORT AVENUE TER',
 'DUNLAP ST',
 'PREBLE ST',
 'WASHBURN ST',
 "JAMES O'NEILL",
 'MALCOLM X BLVD',
 'DRY DOCK AVE',
 'DARLING ST',
 'ATHOL ST',
 'BRENT ST',
 'BRIGHAM ST',
 'FRUIT ST',
 'DEXTER ST',
 'CRESCENT AVE',
 'DUNBAR AVE',
 'SIGOURNEY ST',
 'ACADEMY HILL RD',
 'ATLANTIC ST',
 'UNION ST',
 'SAINT BOTOLPH ST',
 'BOWDOIN SQ',
 'FAYSTON ST',
 'YARMOUTH ST',
 'NEPONSET AVE',
 'WAINWRIGHT ST',
 'CROSSMAN ST',
 'HARRY AGGANIS WAY',
 'MARION ST',
 'PARK VALE AVE',
 'SOUTHERN AVE',
 'THOMAS ST',
 'WALDEMAR AVE',
 'LAWRENCE AVE',
 'RUTHERFORD AVE',
 'BROOKSDALE RD',
 'CROSS ST',
 'YAWKEY WAY',
 'FRAZER ST',
 'BURR ST',
 'TRAIN ST',
 'PARIS ST',
 'HOBART ST',
 'WARRENTON ST',
 'P ST',
 'STRONG PL',
 'HIGHFIELD TER',
 'BELDEN ST',
 'UPTON ST',
 'FAWNDALE RD',
 'FAY ST',
 'M ST',
 'LINDEN ST',
 'WELLINGTON ST',
 'SILVER ST',
 'W CEDAR ST',
 'TELFORD ST',
 'POST OFFICE SQ',
 'WOODRUFF WAY',
 'CENTRAL WHARF',
 'SHANDON RD',
 'KEARSARGE AVE',
 'ELTON ST',
 'BLENFORD RD',
 'PHIPPS ST',
 'TACOMA ST',
 'BELLFLOWER ST',
 'MERCIER AVE',
 'SYDNEY ST',
 'W SECOND ST',
 'BOARDMAN ST',
 'LEO M BIRMINGHAM PKWY',
 'MYSTIC ST',
 'INTERVALE ST',
 'SMITH ST',
 'TERRACE ST',
 'SOUTH POINT DR',
 'PLANT CT',
 'KINGBIRD RD',
 'SUMMIT AVE',
 'BURROUGHS ST',
 'W FOURTH ST',
 'FOUNTAIN ST',
 'S BREMEN ST',
 'COURT ST',
 'LEEDS ST',
 'STOCKTON ST',
 'EASTON ST',
 'COMMERCIAL WHRF E',
 'PRESCOTT ST',
 'JAMAICA PL',
 'ELM HILL AVE',
 'MALLON RD',
 'HIAWATHA RD',
 'PARKTON RD',
 'AGUADILLA ST',
 'ROCKVIEW ST',
 'HUDSON ST',
 'SCHROEDER PLZ',
 'ALLEN ST',
 'ANNUNCIATION RD',
 'WESTFORD ST',
 'ARMANDINE ST',
 'FOREST HILLS AVE',
 'FLORENCE ST',
 'ANTHONY RIP VALENTI WAY',
 'EDGERLY PL',
 'CENTRAL ST',
 'DECATUR ST',
 'DOWNER AVE',
 'HORAN WAY',
 'REDFORD ST',
 'SAINT MARKS RD',
 'SAINT ALPHONSUS ST',
 'HAYWARD PL',
 'SAN JUAN ST',
 'HEBRON ST',
 'GRAY ST',
 'WAVERLY PL',
 'OAK SQUARE AVE',
 'WILCOCK ST',
 'DARLINGTON ST',
 'ARLINGTON ST',
 'FEDERAL ST',
 'VIRGINIA ST',
 'AMES ST',
 'KNAPP ST',
 'E LENOX ST',
 'BRAINTREE ST',
 'MOUNT VERNON ST',
 'INDIA ST',
 'ETNA ST',
 'WILMINGTON AVE',
 'ARMINGTON ST',
 'GEORGETOWNE DR',
 'HUMPHREYS PL',
 'TOBIN RD',
 'HOLTON ST',
 'NEW ENGLAND AVE',
 'WELLES AVE',
 'WINTHROP ST',
 'CARSON ST',
 'SHAFTER ST',
 'BOSTON HARBOR',
 'CORTES ST',
 'MARCELLA ST',
 'ASHLAND ST',
 'MARGINAL ST',
 'MINNIE CT',
 'CORONA ST',
 'COREY ST',
 "TIBBETT'S TOWN WAY",
 'SHERWOOD ST',
 'DEARBORN ST',
 'SAVIN ST',
 'CHARLES ST S',
 'COLUMBUS',
 'WOODMAN ST',
 'MARK ST',
 'ALVAH KITTREDGE PARK',
 'BRADLEE ST',
 'BROMFIELD ST',
 'OAK ST',
 'PRINCE ST',
 'AYLES RD',
 'THOMAS PARK',
 'DAVID G MUGAR WAY',
 'SUNCREST RD',
 'MOUNT IDA RD',
 'E BROOKLINE ST',
 'LAVAL ST',
 'FOREST PL',
 'GENERAL LAWRENCE LOGAN WA',
 'SHEAFE ST',
 'METROPOLITAN AVE',
 'MOZART ST',
 'COMO RD',
 'COLONEL MICHAEL J. MCDONO',
 'PARMENTER ST',
 'MOULTON ST',
 'MAIN ST',
 'RADCLIFFE RD',
 'ALEXANDER ST',
 'FIRTH RD',
 'MOUNT PLEASANT AVE',
 'COLCHESTER ST',
 'WOODGLEN RD',
 'HICHBORN ST',
 'GUILD ST',
 'ROBEY ST',
 'NELSON ST',
 'VICTORY RD',
 'ASHLEY ST',
 'FRONTAGE RD',
 'JACKSON AVE',
 'TILESTON ST',
 'GREYCLIFF RD',
 'RUNNING BROOK RD',
 'NORMANDY ST',
 'CODMAN PARK',
 'SEVENTH ST',
 'BABE RUTH PARK DR',
 'BRAINERD RD',
 'JASON TER',
 'MINTON ST',
 'CENTRAL SQ',
 'LEROY ST',
 'KING ST',
 'CONSTITUTION RD',
 'PENNIMAN RD',
 'DOWNEY CT',
 'WENHAM ST',
 'ALDRICH ST',
 'SAFFORD ST',
 'TENNIS RD',
 'BROWN AVE',
 'GREENWOOD ST',
 'ROCKLAND AVE',
 'DUNMORE ST',
 'NEWMARKET SQ',
 'REMINGTON ST',
 'RICHARD TER',
 'S WHITNEY ST',
 'SPRING LN',
 'BIRCHCROFT RD',
 'BUSSEY ST',
 'GASTON ST',
 'SAINT THOMAS MORE RD',
 'PROCTOR ST',
 'MAGNOLIA ST',
 'EXETER ST',
 'ANNAFRAN ST',
 'BOWDOIN AVE',
 'PHILLIPS ST',
 'CLEAVES ST',
 'OTIS ST',
 'JONES AVE',
 'JAMAICAWAY',
 'STONEHURST ST',
 'ASTICOU RD',
 'W SIXTH ST',
 'CARROLL ST',
 'WACHUSETT ST',
 'CUSHING AVE',
 'CALLENDER ST',
 'WALNUT PARK',
 'BRADSTON ST',
 'WHITFORD ST',
 'GARDNER ST',
 'GREENVIEW AVE',
 'LEYDEN ST',
 'HAVERFORD ST',
 'WEBSTER ST',
 'NEW HAVEN ST',
 'BAKER AVE',
 'W WALNUT PARK',
 'W DEDHAM ST',
 'ITASCA ST',
 'TRUSTMAN TER',
 'CAROL CIR',
 'SAWYER AVE',
 'BOSWORTH ST',
 'CHICKATAWBUT ST',
 'TOPEKA ST',
 'WHITING ST',
 'AMES WAY',
 'CAPEN ST',
 'FLAHERTY WAY',
 'WOODBOLE AVE',
 'INTERNATIONAL PL',
 'CUMSTON ST',
 'WILLOW ST',
 'CORINTH ST',
 'E SIXTH ST',
 'RUXTON RD',
 'JOHNSWOOD RD',
 'FAIRLAND ST',
 "O'MEARA CT",
 'GERARD ST',
 'BREMEN ST',
 'PERCIVAL ST',
 'SHABAZZ WAY',
 'BRADDOCK PARK',
 'NECCO CT',
 'CUNNINGHAM ST',
 'WIGGLESWORTH ST',
 'EDSON ST',
 'HENCHMAN ST',
 "LOUDER'S LN",
 'SPEEDWELL ST',
 'JAMAICA ST',
 'BRADSTREET AVE',
 'COLEBROOK ST',
 'BLACKWOOD ST',
 'ANTWERP ST',
 'GRIMES ST',
 'LORING ST',
 'PERTH ST',
 'CUMMINGS ST',
 'COLORADO ST',
 'GREENBRIER ST',
 'ENDICOTT ST',
 'BROOKLEDGE ST',
 'STOUGHTON ST',
 'PORTLAND ST',
 'PALACE RD',
 'EASTBURN ST',
 'EDGERLY RD',
 'NEW ST',
 'GLENCOE ST',
 'ALLERTON ST',
 'WENDOVER ST',
 'KENWOOD ST',
 ...]

In [41]:
df.groupby("STREET")["DISTRICT"].unique()

STREET
 ALBANY ST                 [D4]
 BLUE HILL AVE             [B2]
 COLUMBUS AVE              [D4]
 COMMONWEALTH AVE         [D14]
 MASSACHUSETTS AVE         [C6]
                         ...
YUILL CIR                 [E18]
ZAMORA CT                 [E13]
ZAMORA ST                 [E13]
ZEIGLER ST             [B2, B3]
ZELLER ST                  [E5]
Name: DISTRICT, Length: 4643, dtype: object

In [42]:
street_mode = (
    df.groupby("STREET")["DISTRICT"]
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
    .to_dict()
)

In [49]:
# for district
# Step 1: Street-wise most common District (MODE)
street_district_mode = (
    df.dropna(subset=["STREET", "DISTRICT"])
      .groupby("STREET")["DISTRICT"]
      .agg(lambda x: x.mode().iloc[0])
)

# Step 2: Fill missing District using Street
df.loc[
    df["DISTRICT"].isna() & df["STREET"].notna(),
    "DISTRICT"
] = df.loc[
    df["DISTRICT"].isna() & df["STREET"].notna(),
    "STREET"
].map(street_district_mode)
ra_district_mode = (
    df.dropna(subset=["REPORTING_AREA", "DISTRICT"])
      .groupby("REPORTING_AREA")["DISTRICT"]
      .agg(lambda x: x.mode().iloc[0])
)

df.loc[
    df["DISTRICT"].isna(),
    "DISTRICT"
] = df.loc[
    df["DISTRICT"].isna(),
    "REPORTING_AREA"
].map(ra_district_mode)

In [44]:
df.isna().sum()

INCIDENT_NUMBER           0
OFFENSE_CODE              0
OFFENSE_CODE_GROUP        0
DISTRICT               1430
REPORTING_AREA            0
OCCURRED_ON_DATE          0
STREET                10505
Lat                   19359
Long                  19359
NAME                      0
dtype: int64

In [45]:
ra_district_mode = (
    df.dropna(subset=["REPORTING_AREA", "DISTRICT"])
      .groupby("REPORTING_AREA")["DISTRICT"]
      .agg(lambda x: x.mode().iloc[0])
)

df.loc[
    df["DISTRICT"].isna(),
    "DISTRICT"
] = df.loc[
    df["DISTRICT"].isna(),
    "REPORTING_AREA"
].map(ra_district_mode)

In [46]:
import numpy as np

# 1️⃣ Mode STREET for each (DISTRICT + REPORTING_AREA)
street_map = (
    df.dropna(subset=["STREET"])
      .groupby(["DISTRICT", "REPORTING_AREA"])["STREET"]
      .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan)
)

# 2️⃣ Create Series aligned with df rows
street_fill = df.apply(
    lambda r: street_map.get((r["DISTRICT"], r["REPORTING_AREA"]), np.nan),
    axis=1
)

# 3️⃣ Fill STREET using that Series
df["STREET"] = df["STREET"].fillna(street_fill)

# 4️⃣ Fallback: DISTRICT-level mode
district_mode = (
    df.dropna(subset=["STREET"])
      .groupby("DISTRICT")["STREET"]
      .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan)
)

df["STREET"] = df["STREET"].fillna(df["DISTRICT"].map(district_mode))

In [47]:
import numpy as np
import pandas as pd

# 1️⃣ DISTRICT + STREET → mode Lat & Long
ds_map = (
    df.dropna(subset=["Lat", "Long"])
      .groupby(["DISTRICT", "STREET"])[["Lat", "Long"]]
      .agg(lambda x: x.mode().iloc[0])
)

# 2️⃣ STREET → mode Lat & Long
street_map = (
    df.dropna(subset=["Lat", "Long"])
      .groupby("STREET")[["Lat", "Long"]]
      .agg(lambda x: x.mode().iloc[0])
)

# 3️⃣ DISTRICT → mode Lat & Long
district_map = (
    df.dropna(subset=["Lat", "Long"])
      .groupby("DISTRICT")[["Lat", "Long"]]
      .agg(lambda x: x.mode().iloc[0])
)

# 4️⃣ Fill Lat & Long safely
for idx, row in df.loc[df["Lat"].isna() | df["Long"].isna()].iterrows():

    if (row["DISTRICT"], row["STREET"]) in ds_map.index:
        df.loc[idx, "Lat"]  = ds_map.loc[(row["DISTRICT"], row["STREET"]), "Lat"]
        df.loc[idx, "Long"] = ds_map.loc[(row["DISTRICT"], row["STREET"]), "Long"]

    elif row["STREET"] in street_map.index:
        df.loc[idx, "Lat"]  = street_map.loc[row["STREET"], "Lat"]
        df.loc[idx, "Long"] = street_map.loc[row["STREET"], "Long"]

    elif row["DISTRICT"] in district_map.index:
        df.loc[idx, "Lat"]  = district_map.loc[row["DISTRICT"], "Lat"]
        df.loc[idx, "Long"] = district_map.loc[row["DISTRICT"], "Long"]

In [48]:
df.isna().sum()

INCIDENT_NUMBER       0
OFFENSE_CODE          0
OFFENSE_CODE_GROUP    0
DISTRICT              0
REPORTING_AREA        0
OCCURRED_ON_DATE      0
STREET                0
Lat                   0
Long                  0
NAME                  0
dtype: int64

In [50]:
df

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,DISTRICT,REPORTING_AREA,OCCURRED_ON_DATE,STREET,Lat,Long,NAME
0,I182070945,619,Larceny,D14,808,02-09-2018 13:00,LINCOLN ST,42.357791,-71.139371,LARCENY OTHER $200 & OVER
1,I182070885,619,Larceny,B3,456,03-09-2018 17:17,ELLINGTON ST,42.301546,-71.081182,LARCENY OTHER $200 & OVER
2,I182070816,619,Larceny,C6,185,03-09-2018 12:45,MASSACHUSETTS AVE,42.321987,-71.062807,LARCENY OTHER $200 & OVER
3,I182070777,619,Larceny,C11,388,23-08-2018 13:34,ADAMS ST,42.272306,-71.067214,LARCENY OTHER $200 & OVER
4,I182070707,619,Larceny,D14,782,02-09-2018 23:12,GORDON ST,42.352935,-71.140501,LARCENY OTHER $200 & OVER
...,...,...,...,...,...,...,...,...,...,...
313632,I130126035-00,338,Robbery,C11,252,09-02-2016 13:55,SAVIN HILL AV,42.297555,-71.059709,ROBBERY - UNARMED - RESIDENCE
313633,I130041200-00,547,Burglary - No Property Taken,B3,428,07-12-2015 11:38,DIXWELL ST,42.314334,-71.097914,B&E NON-RESIDENCE DAY - NO PROP TAKEN
313634,I120720047-00,334,Robbery,E13,565,17-07-2015 09:23,AMERICAN LEGION HWY,42.289291,-71.103585,ROBBERY - UNARMED - BUSINESS
313635,I120719309-00,530,Commercial Burglary,A1,119,27-07-2015 12:00,BOYLSTON ST,42.352418,-71.065255,B&E NON-RESIDENCE NIGHT - FORCE
313636,I060168073-00,1864,Drug Violation,E13,912,27-01-2018 14:01,CENTRE ST,42.322838,-71.100967,DRUGS - POSS CLASS D - INTENT MFR DIST DISP